### ISSUE TITLE
Feature Suggestion: Multiple playlists and to be able to change playlist when clicking on a song in a different playlist.

### ISSUE THREAD

**Issue by kasslermedmos** [xinnks/xns-audio-player#18]
I would like to have multiple playlists on my start page and if a user clicks in an inactive playlist the songs array should update before the clicked track starts playing.
Thank you for an awesome player!

**Comment by kasslermedmos** [comment]
I managed to get this to work by passing the playlist as an async arg with the updatePlaylist action before running the playTrack action. However now I ran in to the problem of the track duration color in the SongBlock running in both playlists even if only one is playing, just because it is mapped to the currentTrackId number in the playlist. Do you now of any easy way to make a ref to the parent playlist component?
<img width="442" alt="Skärmavbild 2021-03-22 kl  08 38 30" src="https://user-images.githubusercontent.com/18265051/112102893-3cc1cd80-8ba9-11eb-8b55-1167a2be845f.png">

**Comment by xinnks** [comment]
@kasslermedmos I appreciate that you find the player usefull. I'll work on the proposed feature soon, just trying to find time. The issue you faced was due to fact that the UI was never made to take into account the occurence of more than one player object/playlist, it just observes the single hardcodded player object and reacts accordingly.

**Comment by kasslermedmos** [comment]
@xinnks Thank you thank you thank you so much!! This is awesome!!!!

**Comment by xinnks** [comment]
Cheers!! 🍻 @kasslermedmos

**Comment by kasslermedmos** [comment]
Found a little bug: "Cannot set property 'currentTrackDuration' of undefined"
<img width="931" alt="Skärmavbild 2021-04-05 kl  18 01 38" src="https://user-images.githubusercontent.com/18265051/113595421-459ab080-9639-11eb-885d-f8244ecd7f9d.png">

**Comment by kasslermedmos** [comment]
Question: I have separate playlists on different pages e.g. different music profiles. How would you go about replacing the playlist array when clicking on a song in an inactive playlist? At the moment the addPlaylist action only pushes to the existing playlist array.
