### ISSUE TITLE
Installation failure #2

### ISSUE THREAD

**Issue by connecteev** [xinnks/xns-audio-player#2]
@xinnks I'm still seeing an error with a fresh build on my Mac. Let me know if I missed anything here.

$ npm run serve
```
$ npm run serve

> xns-audio-player@0.1.0 serve /Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin                                                    

 ERROR  Failed to compile with 1 errors                                                                                                                                                          10:59:39 AM

 error  in ./src/assets/style.scss

Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~bulma/bulma.sass';
^
      File to import not found or unreadable: ~bulma/bulma.sass.
      in /Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/src/assets/style.scss (line 2, column 1)

 @ ./src/assets/style.scss 4:14-224 14:3-18:5 15:22-232
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.12:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 
```

**Comment by xinnks** [comment]
Have you run "npm i"?

**Comment by xinnks** [comment]
The fault was on my side. Didn't add bulma to dependencies. added now. Notify me on any other issue that might come up or if your build is successful.

**Comment by connecteev** [comment]
@xinnks ta-da! It works now. Thanks for the quick fix. 
This is a phenomenal project, though I'm noticing some minor bugs and lots of areas for improvement. Would you like me to suggest? Let me know if you like me to log issues or some other way to collaborate. I'm new to vue so I hope to dig into *some* of the code myself at some point - let me know if logging issues now would help.

**Comment by xinnks** [comment]
Feel free to collaborate.

**Comment by connecteev** [comment]
@xinnks sounds good, keep an eye out for issues I'll be filing....will find areas for improving this from across the web.

**Comment by xinnks** [comment]
@connecteev Sounds good.
