### ISSUE TITLE
Feature Suggestion: Allow scrubbing (changing the current position within a track)

### ISSUE THREAD

**Issue by connecteev** [xinnks/xns-audio-player#3]
Currently, we have a circular progress bar, but there is no way of scrubbing (changing the current position within a track)

Two possibilities here:
1. Use a horizontal scrubber (this is standard across all kinds of audio and video players). See this https://brugarolas.github.io/bruga-music/artist/Coldplay which is also amazing.

2. Make the circular (green) scrubber work. I'm not sure how difficult or challenging that would be, but it would also have some usability concerns, since users will not be used to scrubbing that way. But if it's easy, it would be cool to get working.

Ideas: https://prnt.sc/o83fcv

**Comment by xinnks** [comment]
I have been quite caught up in stuff for the past two days and actually this is the first time I've logged to github, so pardon the silence. As per this suggestion I think it's valid and I'll be working on it laying towards the first approach. I might add the later as just an additional feature on a later date.

**Comment by connecteev** [comment]
Sounds good, agreed, I think the former approach is more usable and makes sense. If possible I would  "borrow" all of that code from https://brugarolas.github.io/bruga-music/artist/Coldplay

**Comment by xinnks** [comment]
So I've already started working on that part and I'll make a couple of commits later today. And I'm experimenting on using @nightcatsama's [vue-slider-component](https://nightcatsama.github.io/vue-slider-component) with the necessary application.

**Comment by connecteev** [comment]
Sounds good. Btw if you haven't yet, check out https://github.com/iview/iview
It's phenomenal because all the vue components work together. It beats having to install individual components like vue-slider-component, vodal, etc.

**Comment by xinnks** [comment]
I've used iview before (still using in in some scenarios). When I started this project I was just looking for simplicity i.e a lightweight css framework and iview would've been an overkill, thus I opted to use bulma. The additional components just came up later when I had to add some useful features like volume, and now the scrubbing bar (which I've added already in the last commit).

**Comment by connecteev** [comment]
Makes sense about the overkill aspect. Btw I just tried out what you checked in...works great and looks cool.

Do you expect well continue working off this as a base or use bruga-music as a base?

**Comment by xinnks** [comment]
Personally I'd prefer to work off this, initially for the sake of the challenge (I like challenges) and the advantage of knowing own code thus it's easier to know where to prune or add some code in the future. Because honestly looking at this project's code after a while, I know I'll have to come back at it later and do some pruning as there's some unnecessary code that I could simplify in the logic of the player.

**Comment by xinnks** [comment]
And I've been using Vue, Vuex & Vue-router for almost as long as I've been using laravel, so the work can be done in a couple of hours, unless something unexpected comes up.

**Comment by connecteev** [comment]
Sounds great. I wish I was at proficient as you are at Vue / Vuex / Vuerouter. Currently reading documentation and trying to get even simple vue apps to work. I can continue to file enhancements in this project if that would help, though

**Comment by xinnks** [comment]
You'll be proficient in no time, Vue's curve of learning isn't as steep as let's say angular. Ideas are always welcome.

**Comment by xinnks** [comment]
I guess I can close this thread now.

**Comment by connecteev** [comment]
yes and thanks for the quick fix. more coming soon.
