### ISSUE TITLE
Feature Suggestion: Make the player persistent when you navigate across pages

### ISSUE THREAD

**Issue by connecteev** [xinnks/xns-audio-player#4]
Feature Suggestion: Make the player persistent when you navigate across pages 
(I am on Laravel 5.8.* but could apply to any back-end framework)

Examples:
Example # 1: Dev.to
Go to https://dev.to/pod to find a list of podcasts
Click on any of them on the right, then click on any of them and start playing it.
Then either: 
1. click on any other link on dev.to, or
2. click the "back" button on the browser to go back to the previous page.

Notice that:
1. The podcast audio keeps playing with no interruptions.
2. The bottom bar shows up (and stays with you) on every page after that. 
https://prnt.sc/o82b5m

Example # 2: See https://brugarolas.github.io/bruga-music/artist/Coldplay
Start playing and then click on any of the links. The audio keeps playing with no interruptions.
This project is also amazing and already does this (and is also built using vue +vuex + vue router). It would be great to utilize this code and to have this audio player do the same.

**Comment by xinnks** [comment]
A valid suggestion also. From my perspective I think this can be done only with javascript routing, for instance I can implement this in vue using the default [vue-router](https://github.com/vuejs/vue-router), wrapping the player in the root component which will also be wrapping the router-view, thus when one navigates to another view, they won't be changing the state of the player. I'd like to assume that https://dev.to/pod too are using this implementation. If you have any suggestion on how this can be done outside this implementation I'm open to that too.

**Comment by connecteev** [comment]
Seems like this is doing it with Vue, Vuex and Vue Router:
https://github.com/Brugarolas/bruga-music
Think it would be easier to start with that as a base by creating a fork? I have ideas to make that even better than it is....we'd have to replace all the last.fm api's with something generic though.

**Comment by xinnks** [comment]
Nice idea. I can also write generic code that can take care of that in vue, vuex & vue-router. I'll branch out the new features and I'll do some commits in the next couple of days or less and then you can take a look at it and give the necessary feedback where due. Likely you can approach it as you proposed and we'll decide on the approach that we'll see is the most efficient for the project.

**Comment by connecteev** [comment]
Sounds good. I'll let you decide whether to use bruga-music or not (I'm for it because it looks amazing and I'm a fan of the phrase "stand on the shoulders of giants" so why re-invent the wheel when we can work on top of it?)
Anyway I'm open to the approach you propose and look forward to building something cool. Btw, what do you use for your back-end framework,if at all? I'm a fan of laravel 5.8 personally.

**Comment by xinnks** [comment]
At the moment it's laravel, started using it around 3 yrs ago and have been using it since then.

**Comment by connecteev** [comment]
Laravel is great. I know php gets a bad rap but right now it's performance is great
https://www.zend.com/en/resources/php7_infographic
https://dannyvankooten.com/from-go-back-to-php-again/

**Comment by xinnks** [comment]
I think php has always been great. I initially started with generic php before getting into it's frameworks. At first I was afraid of using frameworks as I though there would be some efficiency issues, but I've never seen much difference after switching to them. And I'd say php is standard for most web projects, no need to complicate stuff it isn't necessary..

**Comment by connecteev** [comment]
Agree with that 100%. By the way we should probably create a "demo" Laravel 5.8 project that imports / makes use of this audio player. xns-audio-player could stay in this codebase so it's like a separate module or package.
That way, the audio player can talk to the backend to retrieve audio files via an API. Just a thought, let me know what you think (I know we're going way off topic with this thread)

**Comment by xinnks** [comment]
Yap, way off topic. Actually that's close to what I'm doing locally. I created a music db sort of project with laravel with a vue front-end that fetches the songs from the db through it's API. So I did this laravel project way before I started working on this one, and I had to use a certain node package for a front-end player. The player didn't have the best of UI's so that led to the birth of this project.

**Comment by connecteev** [comment]
Okay, so I have a question about whether our visions are going to align. I just want to create something like https://dev.to/pod, but better and for a different industry (not engineers. 

With this app, would it be possible to have an experience like dev.to/pod with podcasts hosted on [anchor.fm, like this one](https://anchor.fm/potd/episodes/Creating-Our-Own-Lives-evnuj
)? That's where my podcasts are going to be hosted, and I'm going to embed each individual episode into my app using an embed code like:
<iframe src="https://anchor.fm/potd/embed/episodes/Creating-Our-Own-Lives-evnuj/a-a19uj7" height="102px" width="400px" frameborder="0" scrolling="no"></iframe>

The anchor player will be embedded into my page, but I'm hoping the player you are working on will **also** have controls at the bottom bar (exactly like https://dev.to/softskillseng/episode-160-non-manager-1-1s-and-throwing-away-dev-learning when you press play). 
Then when I navigate away from the podcast episode page (click on another link on the site, click back, etc), the bottom bar should persist and the podcast should keep playing.

**Comment by xinnks** [comment]
I think finally it will support persistence in javascript routing instances as I said before. But you can use it however you want and can modify the source code to fit your specific use scenarios. I don't think it will be wise to style it to look like an already existing player but, as I said you can finally modify it to suit your needs. Let this be a base for general use.

**Comment by connecteev** [comment]
Okay, great...well let's see what it looks like with persistence added in, and hopefully I can use it for my needs.

**Comment by xinnks** [comment]
@connecteev I'm done with the persistent player. Check it out and I'd like to hear some feedback.

**Comment by connecteev** [comment]
That was pretty fast. Will take a look and give some feedback now and come back to it later
