### ISSUE TITLE
Suggestion: Instead of custom CSS, use a utility-first CSS framework and a Vue framework for js components (like the slider, progress bar, etc)

### ISSUE THREAD

**Issue by connecteev** [xinnks/xns-audio-player#5]
The page is not responsive and has all kinds of front-end bugs. The biggest thing that will help with this is a suggestion: Instead of custom CSS, use a utility-first CSS framework and a Vue framework for js components (like the slider, progress bar, etc)
This'll take the onus of gruntwork away.

1. Migrate to tailwindcss, which is an amazing utility-first CSS framework for
rapidly building custom designs.
https://github.com/tailwindcss/tailwindcss
(questions on this? let me know)

2. For UI components, use a vue framework. These are my current favorites (took me a while to get this working seamlessly in laravel, attaching code here so it'll take you 0 time)
https://gitlab.com/connecteev/laravel_iview (strongly prefer iView for it's UI)
https://gitlab.com/connecteev/element-in-laravel-starter
Then you have vuetify (not my favorite).

Doing these will be a great next step...and then I can pick specific issues with the UI and report back.

**Comment by xinnks** [comment]
So the UI is the next item on the to-do. Tailwind has been on my mind for some time now and I'd assume it to be a suitable framework to use. Just lacking the familiarity with it as I'm yet to create any project with it, but it sounds interesting.

**Comment by connecteev** [comment]
I suggest starting with this. Adam has an amazing ui for workcation, built entirely with tailwindcss. I wish this was available when I started learning tailwind 6 months ago, because this will save you a ton of time https://github.com/adamwathan/workcation
Private YT video: https://www.youtube.com/watch?v=Mp0f2I-OmpQ

**Comment by xinnks** [comment]
@connecteev Completed switching to TailwindCss.

**Comment by connecteev** [comment]
@xinnks awesome. It doesn't compile though. Also, would you mind updating the readme with any additional instructions needed to get this working?

```
 error  in ./src/components/PersistentPlayer.vue?vue&type=style&index=0&id=314aa488&scoped=true&lang=css&

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'

(@/Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/package.json)
    at load (/Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/node_modules/postcss-load-config/src/plugins.js:28:11)
    at Object.keys.filter.map (/Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/node_modules/postcss-load-config/src/plugins.js:53:16)
    at Array.map (<anonymous>)
    at plugins (/Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/node_modules/postcss-load-config/src/plugins.js:52:8)
    at processResult (/Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/node_modules/postcss-load-config/src/index.js:33:14)
    at config.search.then (/Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/node_modules/postcss-load-config/src/index.js:94:14)

 @ ./node_modules/vue-style-loader??ref--6-oneOf-1-0!./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/PersistentPlayer.vue?vue&type=style&index=0&id=314aa488&scoped=true&lang=css& 4:14-406 14:3-18:5 15:22-414
 @ ./src/components/PersistentPlayer.vue?vue&type=style&index=0&id=314aa488&scoped=true&lang=css&
 @ ./src/components/PersistentPlayer.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/Player.vue?vue&type=script&lang=js&
 @ ./src/Player.vue?vue&type=script&lang=js&
 @ ./src/Player.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.12:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/assets/tooltip.css

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'

(@/Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/package.json)
    at load (/Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/node_modules/postcss-load-config/src/plugins.js:28:11)
    at Object.keys.filter.map (/Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/node_modules/postcss-load-config/src/plugins.js:53:16)
    at Array.map (<anonymous>)
    at plugins (/Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/node_modules/postcss-load-config/src/plugins.js:52:8)
    at processResult (/Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/node_modules/postcss-load-config/src/index.js:33:14)
    at config.search.then (/Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/node_modules/postcss-load-config/src/index.js:94:14)

 @ ./src/assets/tooltip.css 4:14-162 14:3-18:5 15:22-170
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/MainPlayer.vue?vue&type=script&lang=js&
 @ ./src/components/MainPlayer.vue?vue&type=script&lang=js&
 @ ./src/components/MainPlayer.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.12:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/assets/style.scss

Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~tailwindcss/base';
^
      File to import not found or unreadable: ~tailwindcss/base.
      in /Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/src/assets/style.scss (line 2, column 1)

 @ ./src/assets/style.scss 4:14-224 14:3-18:5 15:22-232
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.12:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js



```

**Comment by connecteev** [comment]
Somewhat works if I run 
```npm install tailwindcss --save-dev``` before ```npm run watch``` but I see 6 errors in the console (I'll file a separate issue on that)

1. Update readme with the install instructions 
2. More importantly, add a 'tw-' prefix to tailwindcss (and all styles) so that there's no conflicts between tailwind and any other css we add later.

**Comment by xinnks** [comment]
@connecteev the tailwind issue I guess is specific to tailwind itself because as well as I can't promise that I was thorough with it's documentation, I did follow it's documentation on installation [install-tailwind-via-npm](https://tailwindcss.com/docs/installation/#1-install-tailwind-via-npm) and they didn't specify to 
 use --save-dev, but if doing that works for you I guess that's the solution as I didn't face the problem on neither my local nor remote repos.
Regarding adding 'tw-' to tailwind classes, I can't do that now as that's no small feat and I don't have  the time, quite occupied with some work. If you have the time you can commit a branch with the modifications. I also believe we've fixed a majority of bugs and added some cool features, so kudos to that.

**Comment by connecteev** [comment]
Sounds good, glad we were able to migrate to tailwind, at least. The reason for using the tw- prefix is so that there are no conflicts with other css classes, libraries, etc. 

Here's how to do it all in one shot if you're using an editor like sublime text:

```
You need to append a prefix (tw- in this case):
Note: Do a search and replace (use Regex matching)
Replace:
(rounded|cursor-|no-|items-|justify-|underline-|z-|-mt-|-mb-|-mx-|-my-|-mr-|-ml-|-m-|mt-|mb-|mx-|my-|mr-|ml-|m-|px-|py-|pt-|pb-|pr-|pl-|p-|-px-overflow-|w-|min-w-|max-w-|h-|min-h-|max-h-|border-|border|shadow-|shadow|opacity-|appearance-|cursor-|outline-|pointer-events-|resize-|resize|select-|fill-|stroke-|items-|content-|self-|justify-|order-|bg-|break-|truncate|whitespace-|align-|uppercase|lowercase|capitalize|normal-case|underline|line-through|no-underline|list-|leading-|tracking-|font-|not-italic|italic|subpixel-antialiased|antialiased|text-|invisible|visible|inset-|top-|right-|bottom-|left-|static|fixed|absolute|relative|sticky|overflow-|scrolling-|object-|float-|clearfix|inline-|inline|block|flex-|flex|table-|table|hidden|container)

With:
tw-$1

```

**Comment by connecteev** [comment]
Just checked in the code for a tailwind prefix so there's no conflicts in future. 
Btw, other sites like view-source:https://laracasts.com/ do the same thing.

I did notice that you're using a lot of unnecessary styles and the code needs a lot of refactoring, but this will have to do for now.

**Comment by xinnks** [comment]
Yap, there's lot's of unnecessary fat to cut in there, just haven't found the time to focus solely on this project.
